### ISSUE TITLE
posix imports

### ISSUE THREAD

**Issue by ghost** [fabio-miranda/csv-to-influxdb#17]
python3 csv-to-influxdb.py -i server1.csv -s server5:8086 --create --dbname NewTest --tagcolumns host --fieldcolumns CPU,GPU --metricname name --timecolumn time --timeformat unix
Deleting database NewTest
Creating database NewTest
Traceback (most recent call last):
  File "csv-to-influxdb.py", line 194, in <module>
    args.timezone, args.ssl)
  File "csv-to-influxdb.py", line 77, in loadCsv
    datetime_naive = datetime.datetime.strptime(row[timecolumn],timeformat)
  File "/usr/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '1590335330162702714' does not match format 'unix'

CSV looks like this

name,time,CPU,GPU,host
temperature,1590335330162702714,53.5,53,server1

**Comment by fabio-miranda** [comment]
That is not a valid time format. It should be something like this:
-tf [TIMEFORMAT], --timeformat [TIMEFORMAT]
Timestamp format. Default: '%Y-%m-%d %H:%M:%S' e.g.: 1970-01-01 00:00:00
