### ISSUE TITLE
Import of data failed for influx 1.8.6

### ISSUE THREAD

**Issue by ZKBen** [fabio-miranda/csv-to-influxdb#18]
Hi,

I used your solution quite well, but as I moved to influxDB 1.8.6 it seems that there is an issue with the import of data.
A typical .csv-File-DataLine would like

`2021-05-28T08:00:47.004,49.954104,8.308486,106.100000,39212,3542.5,42127,5000.0,34283,1.842210159999997,161,70.0,2,3,
34283,32.89798135999996,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
,,,,,,,,,,,,,,,,,,,,,,,,,,,,`

As there might be data (floats) between the comma within an earlier line I get a type mismatch error (400) from influx client, as it is now a 'string' (empty one).
Scratching my head the solution was quite simple.

Within the "#open csv"-area there is the following loop:
```
 for f in fieldcolumns:
     v = 0.0
     if f in row:
         if (isfloat(row[f])):
             v = float(row[f])
```

I added an 'elif' to check whether the column is an empty string, if it is, then I skip that field. No it looks like
 ```
   for f in fieldcolumns:
       v = 0.0
       if f in row:
           if (isfloat(row[f])):
               v = float(row[f])
           elif (isbool(row[f])):
               v = str2bool(row[f])
           else:
               v = row[f] # may insert an empty string
       if v:
           fields[f] = v
```
This also should speed up the import, if you have a lot of empty fields (not all messages are scanned at the same time), like in my .csv-files.

Thank you for the great tool

**Comment by fabio-miranda** [comment]
Thank you, merged.
