### ISSUE TITLE
time format issue

### ISSUE THREAD

**Issue by shnabin** [fabio-miranda/csv-to-influxdb#8]
Hi, 

I am new to python. I'm trying to write a csv file to influxdb using cmd prompt in windows 10 and i am receiving the following error, please help me.

csv-to-influxdb.py: error: unrecognized arguments: %H:%M:%S'

C:\Users\admin\AppData\Local\Programs\Python\Python37\Scripts>python csv-to-influxdb.py --dbname test --input D:\mydata\FL_insurance.csv --tagcolumns policyID --fieldcolumns tiv_2011 -tc timestamp -tf '%d-%m-%y %H:%M:%S'
usage: csv-to-influxdb.py [-h] -i [INPUT] [-d [DELIMITER]] [-s [SERVER]]
                          [-u [USER]] [-p [PASSWORD]] --dbname [DBNAME]
                          [--create] [-m [METRICNAME]] [-tc [TIMECOLUMN]]
                          [-tf [TIMEFORMAT]] [-tz TIMEZONE]
                          [--fieldcolumns [FIELDCOLUMNS]]
                          [--tagcolumns [TAGCOLUMNS]] [-g] [-b BATCHSIZE]
csv-to-influxdb.py: error: unrecognized arguments: %H:%M:%S'

my csv time format is d-m-y

**Comment by fabio-miranda** [comment]
If your csv time format is 'd-m-y', you need to use -tf '%d-%m-%y'

**Comment by shnabin** [comment]
Thank you, the issue was with the date format in my csv. Works fine now.

Cheers!!
